language: node_js
node_js: node
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: JNuxCMSOzEYyUNkBh5YPUePjfYzbPx6JJAFP8OFCktZ9r40LyTpsx91An6PVeSnyyK5zIZ9BKJBjxutS78iwMihyO9hj8/cF6X98UKbDW3SpBoT1OLY+rHBHFlx5izVaQBzyedJFNk8AVvy4p8/G9CvTkc5DgwFPlx2pm+CTO/A4DCnWdb4fmLwhKLsr5AdVOt9eOp5fJumSExsk1+JC1kSR6AhSzRfIBAacjXBaEtqYnbS2fqOElNx9cXoMPfL0eRUJXav9R6byMWRXq183EVRhBU1T9DCFOD4UzVRluN7y5g5OTmvLxA3e6Yt2U8K1WFie8Ev3ablOTiSJQ6eQFezNr3LERS4REg83W/oXKoou8bkvV3m/SUQHpvNCZ37lYJfyhfgoA4PUl0GxYznep+IRERO0b+I69pnb5SrtE3wRJFc+P9jasloG0YRE1vweGW9bHfnfym77rhMQS9tvZk7+byZUnacSHSc8+yyz9IT8pgZzevZj5bS/zXajGMUM6udZuIPmCuCWL3Cy4WWpUJDoJqr0AuJ4Lbfz4QYG1Qrr4/p91QS3Kx8NF29eDB0XWs3MRd15X0NO83mtguP4rw0kcK9b6BVQFTms5UYyvjMaZqUR7NPD4wuSWWdJOWfu2m0Yozv4wpe1MvOFJ6BdRQa/aYedw3w0M+u6RTAEUp0=
  app: destino-planning
  on:
    repo: Aaron-Lathrop/destination-client
